### ISSUE TITLE
Update an Achievement Types turns it into an ordinary Post

### ISSUE THREAD

**Issue by smart-fr** [opencredit/badgeos#152]
Hello,

<ol>
<li>Create an Achievement Type and publish it</li>
<li>Edit the Achievement Type (e.g. tick "Show in Menu") and press "Update"</li>
<li>The Edit Post screen displays, saying "Post updated". The Achievement Type has become an ordinary Post, and can't be found in the Achievement Types list anymore.</li>
</ol>

Well, at least on my Wordpress installation.
Has anyone seen this before?

**Comment by tw2113** [comment]
Closing as there has been very little, if any new reports on this one.

**Comment by nezibo** [comment]
I am having this issue, The same results are showing up in my DW Q&A search results.
http://pasteboard.co/1PNMiBVk.png

**Comment by tw2113** [comment]
@nezibo are you sure your getting things converted to posts like the original issue is about, or that your Q&A search results are simply including/searching what looks to be the "step" private post type from within BadgeOS?

**Comment by nezibo** [comment]
I found the items in the wp-posts table, I have removed them and temp removed BadgeOS but im sure I can replicate it if needed or just reinstall for you to see

**Comment by tw2113** [comment]
You're going to, because BadgeOS' achievement types are all post types. The question is if DWQ&A has any limiting for the post types it queries against, or if it's just querying against all post types available, which would be why the 'step' post type is creeping in.

**Comment by nezibo** [comment]
Before it was just showing questions, nothing else so it should be limiting. I also have a ticket with there support for them to research as well. I appreciate the quick support. Now it seems after installing badge os something was changed that threw off the search to include badgeos althought im starting to think its something more on there side, is there anything I can do to help troubleshoot?

**Comment by tw2113** [comment]
Well, I know that all we do is register post types to aid with achievement types. We don't purposely inject ourselves anywhere, especially not targeting this plugin/theme itself.

It's possible their plugin is built to search in all non-"built in" post types. Built in ones would be like "post", "page", "attachment", "nav_menu_item", "revision" and so on.
