### ISSUE TITLE
Conflict with PMPRO  Paidmembershipspro, 404 eror

### ISSUE THREAD

**Issue by mrkellysch** [opencredit/badgeos#162]
When the Badgeos plugin is disabled the checkout works, but  when activated it creates a 404 error. 

Using the "debug wp_plugin" I got the following debug log:

```
Location: https://www.mydomain.co.uk/?page_id=207
Status: 302
Backtrace:
File: /var/www/wp-content/plugins/paid-memberships-pro/includes/init.php
Line: #90
Function: require_once
Arguments:
array(1) {
  [0]=>
  string(72) "/var/www/wp-content/plugins/paid-memberships-pro/preheaders/checkout.php"

```

**Comment by dauidus** [comment]
It seems this issue has still not been resolved, by BadgeOS or Paid Memberships Pro.  In fact, it is an incredibly simple fix - just get rid of the "Levels" Achievement Type in BadgeOS (or, rename the slug).

**Comment by tw2113** [comment]
By default, only "badges" gets created with the BadgeOS core plugin. It's the Badgestack starter addon that has a "levels" achievement type included to help get peoples feet off the ground, if I recall correctly.

**Comment by dauidus** [comment]
Oops... you are correct, sir!  I'll contact that plugin's author about the issue.  :-)

My apologies.

**Comment by tw2113** [comment]
All the same people as BadgeOS core.

https://wordpress.org/plugins/badgeos-badgestack-add-on/

Forgive me for sounding a bit dismissive, but I don't view it as as huge of an issue as it may seem. I'd call PMPro's need for "level" as much more integral than Badgestack's which is just quick start help. Remove the Badgestack create'd one and carry on :)

**Comment by dauidus** [comment]
I agree that its not that big of an issue.  But, our small team spent a couple of hours troubleshooting this issue on a development site last night and this morning.  I can't help but feel that this issue could have been completely thwarted by some small attention to detail - I'm sure we're not the only ones to come across this issue.  

I realize the impossibility of trying to fix every conflict for every plugin out there.  But, as BadgeOS and Paid Memberships Pro are commonly used together, it seems you'd want to help those users out by preventing wasted time troubleshooting a silly issue.

Just an opinion, though - and, as a plugin developer myself, I completely understand where you're coming from.  :-)

**Comment by tw2113** [comment]
BadgeOS + PMPro isn't the issue though, it's just when the Badgestack addon comes into play, and there's no guarantee that all 3 would be used. There's also cases where someone would like to include a 'level' achievement type with some sample content, and has no plan to use PMPro.

I feel, even with the time your team spent debugging it, it's an infrequent enough conflict to just handle on the case-by-case basis as they come in.

**Comment by dauidus** [comment]
I'm completely fine with that.  After all, we have used BadgeOS a lot in the past, but never with PMPro.  Perhaps then, you could add a small section under the FAQ on the plugin's repository pages quickly explaining the problem and providing the fix.  I think that would have helped us out a lot.

Either way, BadgeOS is a great plugin!  Thanks for all the work you've put into it, and we look forward to seeing what comes next!  :-)

**Comment by muhammadatif415** [comment]
I have found solution , just rename achievement type "level" . Every thing will work fine
