### ISSUE TITLE
Broken "No badges to display at this time" in badgeos_achievements_list short code

### ISSUE THREAD

**Issue by scarpenter-avenues** [opencredit/badgeos#192]
When using the badgeos_achievements_list short code on multisite network the "No badges to display at this time" message displays even when there are badges displayed.

We located the issue in ajax-functions.php

The closing bracket on line 167 should be ABOVE the "display a message for no results" conditional. We put it on line 152, and it fixed the issue.

**Comment by tw2113** [comment]
I'm having trouble visualizing this being an issue any more, to be honest. It's also been the only report I know of for this. I think we're safe to close it, and if someone else comes back with the same issues, we can re-open and re-investigate.
