### ISSUE TITLE
ACHIEVEMENTS: Remove 2-digit limitation on maximum earnings field

### ISSUE THREAD

**Issue by tw2113** [opencredit/badgeos#334]
This came in via our support email:

--------------

Full Name:      *redacted*
E-mail:         *redacted*

Question/Comment:
Hello there!

I am working on a community site with my partner and we're using BadgeOS on the site as a fun addon, people love getting achievements.

We did however stumble upon a little problem when we're creating the badges.

The problem is that when we create the steps required to win this or that badge, there seems to be a maximum input of 2 digits in the "Time(s)" field.

This menas that the highest possible badgechallenge we have is 99.

For example "write 99 forumposts"... Now passing 99 is obviously going to take a very short time, and people will eventuelly reach up to the thousands or more.

So, why is there a limit for us to just 2 numbers in the time(s) field? It would
be nice to be able to create a badge for those who has, for example, posted 5000 times, and not just end the postbadge at 99.

That's all. Thank you! :)

**Comment by EyesX** [comment]
This got me a bit baffled to say the least. With the Community Add-on activated this is a real deal breaker. Sure you can set up levels of badges to earn, let's say a badge for 1000 replies, but even then, an odd number as the limit makes no sense.

Is there any workaround? Where is the limit set? Is it only due to a `maxlength="2"` on the field?

**Comment by tw2113** [comment]
I was not around for the original design decisions, so I don't know why the limit was put in place.

I also don't know of any workaround that is for sure tested, and I'd need to look through the source to check exactly how and where it's enforced.

**Comment by costyclan** [comment]
Is there a workaround for this yet?

**Comment by asahi-badgeos** [comment]
Hi @costyclan ,

We should be able to resolve this in our next release.  I will keep you updated.

**Comment by andytgeezer** [comment]
I need this as well. I run a 365 challenge where people post 365 times in a year. The badge gets awarded on the 365th post, but with this limit in place the whole thing becomes rather pointless. Can't find any workaround to it either. 

Surely a 99 limit means that BadgeOS quickly outlives it's usefulness?

**Comment by wtca** [comment]
@costyclan , @andytgeezer we have upgraded this plugin in version 1.4.8.2 to now allow a 3 digit maximum.

**Comment by asahi-badgeos** [comment]
@costyclan , @andytgeezer we have upgraded this plugin in version 1.4.8.2 to now allow a 3 digit maximum.

**Comment by andytgeezer** [comment]
Super - thanks for the fix.
