### ISSUE TITLE
Cannot set to 0 "Maximum Earnings"

### ISSUE THREAD

**Issue by efuentesp** [opencredit/badgeos#380]
Hello, I'm trying to set to 0 the "Maximum Earnings" but it doesn't work, every time I tried to set to 0 it always keep 1. I can set to any other value like 100, but no 0.

**Comment by Sym-O** [comment]
Hi ! 
I'm facing this issue right now. I haven't built my full understanding of this problem, but it seems to me more of an annoying bug than an Enhancement to be made, don't you think ?

**Comment by tw2113** [comment]
CMB is evaluating string "0" to true when checked for empty(). We should probably change this to something like -1 or something else to imply no limit.

**Comment by scottbasgaard** [comment]
Any updates on this one?

**Comment by tw2113** [comment]
Nope

**Comment by scottbasgaard** [comment]
@tw2113 any way I can help? Where would you recommend I start?

**Comment by tw2113** [comment]
The discussion in #515 is closely tied to this one, really. My biggest concern is making sure we don't break what existing sites we have if we were to push one solution out the door. We don't have extensive unit tests which is both understandable and sad at the same time.

**Comment by asahi-badgeos** [comment]
This item was resolved in version 1.4.8.  The field has been updated to use -1 to specify unlimited earnings.

**Comment by scottbasgaard** [comment]
@asahi-badgeos great!
