### ISSUE TITLE
Default thumbs up image still being loaded repeatedly in media library

### ISSUE THREAD

**Issue by tw2113** [opencredit/badgeos#383]
/plugins/badgeos/includes/achievement-functions.php line 696

May be best to check for an attachment with the same GUID or so, and if we have one already, grab that one's ID and use it instead of sideloading one each time.

**Comment by ChristinaR** [comment]
My WP 4.1 Media Library is grayed out when BadgeOS 1.4.3 is activated? We need to resolve. Any suggestions?

**Comment by tw2113** [comment]
Could you please start a support thread, if you haven't already, over on the BadgeOS forums on wordpress.org? We'll look into that there.

**Comment by tw2113** [comment]
Fixed in 017a1ed18e696298f6fb8582bcac19df7b4dad49
