### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by kendalcollege** [opencredit/badgeos#384]
Hi Folks

love the badgeOS system, but for some reason are now experiencing the following issue when getting an API

There was an error getting a Credly API Key: Problem with the SSL CA cert (path? access rights?)

anyone have any ideas please, many thanks

**Comment by tw2113** [comment]
Closing. If it's still an issue, please start a thread on the BadgeOS forum on wordpress.org and we'll get it looked at there.
