### ISSUE TITLE
Groups Actions - Addons Ideas

### ISSUE THREAD

**Issue by X-Raym** [opencredit/badgeos#385]
Hi ! 
I wanted to share my ideas about an add-on feature for BadgeOS. It could also be integrated inside the base plugin, that's why I put it here; 

Context : 
When you teach to a lot of people, you have groups. It could be working groups, groups of people wich have something in common, groups of age... Well you have groups. 

And because some course are integrated with some "in real life" events (such as classrooms), 

it would be nice to have group actions, such as 
- give badge X to Y people 
- delete badge  X to Y people 
- give X point to Y people 
- substract X point to Y people

/based on role or capabilities, or with a filterable checkbox user list.

once again, this critical issue has to be fix first https://github.com/opencredit/badgeos/issues/378, but I hope you (BadgeOS / Credly Team or other developpers) will find the idea interesting. 

The coolest thing would be an integration with the awesome Groups WordPress plugin. https://wordpress.org/plugins/groups/ 

What do you think of that ? :)

**Comment by danielmt2k** [comment]
Hi, 

Agree with @X-Raym 

When you have groups, there's the need to be able to issue a badge to a group, instead just an individual.

For example, a gaming website with tournaments where users play within groups. You need to issue a badge to the winner groups.

Thanks.

**Comment by roughwriters** [comment]
+1

Would also be nice to have a group leaderboard as well, though that's a separate issue.

**Comment by X-Raym** [comment]
@roughwriters 
Funny that you bump this rigth now, cause I am building something, I started just few hours ago !
it is very basic but it works.
You can assign a user role, define an assignement ID and a points offset, and it will be set to all users with that user role
That said, I'm not an advanced wordpress plugin developper so I don't think I will be able to push it very far.

**Comment by roughwriters** [comment]
Whoa, weird timing!

Let me know how it goes. :)

**Comment by X-Raym** [comment]
Sure, I'll tell you ! It goes slowly but surely :P

**Comment by X-Raym** [comment]
Well it works alreayd pretty nicely but there is two little things I don't understand.

@tw2113 
Can you please take a loot at this issue ?
https://github.com/opencredit/BadgeOS-Boilerplate-Add-on/issues/2
I get 404 error when I try to put a link under BadgeOS Menu and I really don't understand why.

**Comment by X-Raym** [comment]
Ok sometimes we just need to make a break. I solve that problem :P

One final one : I put all my code in the BadgeOS class (from the plugin boilerplate) and now my admin form doesn't behave like it did before (and so, it doesn't work anymore)... hmm...

**Comment by tw2113** [comment]
which admin form? Able to share your entire code for what you're doing? May be able to offer some pointers.

**Comment by X-Raym** [comment]
In fact, I created a form on a new admin page.
Here what it looks like:
https://monosnap.com/file/gubsFgJvJe652VjQjV62JBX0B5kWaG.png

In the previous version of the add-on, I used another class constructor from another plugin (I didn't find the BadgeOS boilerplate at this time), it works fine (the forms actually works, and infos were send to the database) and then I tried to make it works with the BadgeOS template, but my form doesn't work anymore.

From the file badgeos-group-actions.php (only php file of the plugn)

	<form method="post" action="badgeos-group-actions.php" enctype="multipart/form-data">
		<?php wp_nonce_field( 'badgeos-group-actions', '_wpnonce-badgeos-group-actions' ); ?>
                
		<div class="points">
			<h4><label for="Give_points"><?php _e( 'Points Offset', 'badgeos-group-actions' ); ?></label></h4>
			<p><input type="text" value="0" name="give_points" /></p>
		</div>
		
		
		<p class="submit">
			<input type="hidden" name="page" value="badgeos-group-actions.php" />
			<input type="submit" class="button-primary" value="<?php _e( 'Submit', 'badgeos-group-actions' ); ?>" />
		</p>

and to treat the request, it looks like
	public function badgeos_group_actions() {
		if ( isset( $_POST['_wpnonce-badgeos-group-actions'] ) ) {
			check_admin_referer( 'badgeos-group-actions', '_wpnonce-badgeos-group-actions' );
			/* CODE*/
			/**
			* Final Action
			*/
			wp_redirect(  admin_url( 'users.php?page=badgeos-group-actions&m='.$user_count ) );
			exit;
		
		}

before, it redirects me as expected on the same page ->
http://127.0.0.1:4001/wordpress/wp-admin/admin.php?page=badgeos-group-actions
now it goes to a white screen ->
http://127.0.0.1:4001/wordpress/wp-admin/admin.php

Do you see something wrong in my form ?
Thanks for the help :)

**Comment by tw2113** [comment]
You won't need all of it, but maybe check out the admin-settings.php file from BadgeOS core to see how we have our settings page set up, and copy/paste from there. I believe you're trying to utilize the settings API above, but correct me if not.

**Comment by X-Raym** [comment]
hmmm it seems that your form actions is option.php, 
I take a look at wordpress codex and it seems that this kind of points are reserved for settings that are permanent on the site. My form is more a "do that once" kind of form, not a "settings" so it is a bit different.
But it works with my previous constructor hmmm...
If you want to digg that further, maybe can I show you the code (working version, and boileplate version <- which is better because of the "badgeos" template function to check for dependencies).

**Comment by X-Raym** [comment]
I DID IT !!

**Comment by tw2113** [comment]
Personally i prefer leaving hooks outside of the constructor, and running a hooks method right after initialization of the object. It works either way though.

**Comment by X-Raym** [comment]
That make sense. I'll see if I have the courage to mess with that later, wanted to make things more user-oriented for the moment.

**Comment by X-Raym** [comment]
Hi @tw2113 ,
I try to loop all achievement title in an dropdown menu in my form but I just noticed that I can't have more than 5 items.
I checked it seems that the badgeos_get_achievements function only get 5 items.

Here is my code:

				//loop through all registered achievements
				$achievements = badgeos_get_achievements(); // Get achievement in an array of objects
				foreach ( $achievements as $achievement ) { // Convert Array of objects in simple assosiative table
					
					$title = get_the_title( $achievement->ID ); // get achievement title

					$achievement_array[$title] = $achievement->ID; // here is the assosiative table
				}
				

How could I make this function returned more than 5 achievement, but all of them ?

thanks :)

**Comment by tw2113** [comment]
Apparently a more widespread issue than I first thought: https://wordpress.org/support/topic/achievement-list-not-displaying-all-achievements?replies=4

**Comment by X-Raym** [comment]
Oh well indeed !

I don't know when the issue can came from, because when using the shortcode [badgeos_achievements_list], It seems that we can have a lot more items (I don't know the limit), and it is not related to General->Reading Post limits.

Can you please let me know if you find another way to loop on all achievement ?
It will help a lot :)

Thanks !

**Comment by tw2113** [comment]
As noted in https://wordpress.org/support/topic/achievement-list-not-displaying-all-achievements?replies=9#post-7552679, passing in any extra parameters for get_posts()/WP_Query should take to the request in the end. We only provide a few defaults, including the typo'd field you pointed out.

**Comment by X-Raym** [comment]
have you seen the wordpress thread ? I found the source issue and be able to correct it !
while doing that, I saw a typo error in the funxtion, i created a pull request for you.

**Comment by tw2113** [comment]
Yeah I saw it all, however that's actually ending up being a big PR change, because of the fact that it affects a number of things in queries. 3 out of 4 internal calls to badgeos_get_achievements() don't set their own parameter and intend to rely on the intended default of 'any' BUUUUUUUT that's not getting set because of that typo.

You can see where we check for the value with the correct spelling inside `badgeos_get_achievements_children_join()` and `badgeos_get_achievements_children_where()`, both of which are callbacks for query filters. I'm praying that fixing it is not going to break anything, but will fix bugs that we may have going on that haven't been figured out yet.

**Comment by X-Raym** [comment]
Here is how far I get for the moment. 

https://www.youtube.com/watch?v=4vR0ur3usVk

I wil change the Award selction by putting checkboxes so we can assign / revoke multiple asisnements at the same time (and with a checkbox to select/unselect all of them).
I did the same thing for users.
In fact I wonder if I will not also do the same thing with Roles and Capabilities. It will be more flexible :P

I also plan to ass a "set points" field.

Do you like it ? :)

**Comment by X-Raym** [comment]
Hi @tw2113 ,

When calling badgeos_award_achievement_to_user() with WP_DEBUG on, I get some errors message :
https://www.dropbox.com/s/rqyl8e2bagmjymy/admin.php.zip?dl=0
The actions do works as expected but I think it has to have some ways to check if the credly is activated or not in order to prevent error. (as far as I understoof from these error reports).
Let me know if you want me to open a new issue thread, or if you think it is an error in my plugin.

**Comment by tw2113** [comment]
Could you paste what the actual errors are? not sure if that link is supposed to prompt me to download something or not

**Comment by X-Raym** [comment]
Oops, dropbox sync problem.
I paste the HTML report on pastebin.
http://pastebin.com/He14BJbZ
Just copy paste into a new file, rename with .html, and open in your browser :)

**Comment by X-Raym** [comment]
@tw2113 
I put the page on my website.
Far more easier for you to consult :)

http://extremraym.com/cloud/report.html

**Comment by tw2113** [comment]
Those are all originating from your plugin :P Looks like the common denominator is BadgeOS_Addon->badgeos_group_actions( ) Looks like your plugin isn't in github yet, so I can't look things over directly if needed.

**Comment by X-Raym** [comment]
@tw2113 
I see. Bad news. ^^
Oh yes it is not on github because
-I wanted to be sure it is safe to use before sharing version ( development version could reset points to 0 or that kind of things, it is all stable now, but yes, still in bug tracking phase (these ones may be the last)).
-I think it could be interesting to release it as a premium add-on (but with a fair price). It can be a positive experience, and because it can do things that save a lot of times and effort, it may even worth it :) What do you think ?

Thanks for proposing taking a look at it. If you still want to take a look at it, I can upload it on a private repo on bitbuckets (I don't have private repo with github).

**Comment by tw2113** [comment]
Makes sense. Emailing a zip directly would work as well, and I can provide my email.

**Comment by X-Raym** [comment]
Nice :) let me know where I can find your email :P

**Comment by tw2113** [comment]
michael @ webdevstudios dot com will reach me.

**Comment by X-Raym** [comment]
@tw2113 
mail sent !

**Comment by X-Raym** [comment]
Some dev news:
*Added recursive deletion to delete all achievement of one certain type
*Optional options to revoke points associated to an achievement when removed now works
*Added an option to not give an achievement to a user if it will make it go beyond the maximum earning limit of the achievement
*added clickable-draggable checkboxes
*added spinner loading and submit button hidding when clicking on submit
*HTML and PHP enhancement (accessibility and performance)

There is still some few thing I am thinking about, such as deletion of empty achievement in users meta (achievement which have been deleted leaves achievement data in users meta).

I also developed a second BadgeOS plugin very handy, which allows some nice things in Admin (and make the development easier), I'll talk about it later, but it also answers some other feature requests.

**Comment by X-Raym** [comment]
For those who are interested, the plugin is almost ready for use in production.
It is still in beta for now. You can see that on my website.
BadgeOS Bulk Actions Add-On[http://www.extremraym.com/en/downloads/badgeos-bulk-actions-add-on/]

**Comment by tw2113** [comment]
Just a curious suggestion/question. Willing to offer users a small discount for trying when still in beta?

**Comment by X-Raym** [comment]
For the moment, the beta is 'private' but I may indeed open it very soon if people are interested by the betatesting.
That said... Check your emails :P

Do you know how long it takes to learningtimes to review add-ons ?

**Comment by tw2113** [comment]
No I don,t regarding review time.

**Comment by X-Raym** [comment]
@tw2113 
I send you a 100% discount discount code by e-mail if you want to test the add-ons. It is my way to thank you for all the help you gave me :)

**Comment by tw2113** [comment]
I saw, I just don't have a need to utilize quite yet.

**Comment by X-Raym** [comment]
@tw2113 
Oh, I'm sorry to hear that my gift has no use for you... Well, the offer stay opened if you change your mind.
I will wait a week until learningtimes review but I have to admit that without their approval and support, it will hard to promote the plugins.
BadgeOS blog is also dead since more than one year... I wonder if learningtimes is still actively supporting BadgeOS.

**Comment by tw2113** [comment]
My extension focus etc is primarily just the official extensions/core, since that's where I need to provide the support at. It's nothing against you.

Everything is still supported, they haven't abandoned anything by any means.

The LearningTimes twitter account is a bit inactive, but the Credly account is active still.

**Comment by X-Raym** [comment]
@tw2113 
Isn't Credly just a partner of LearningTimes ?

**Comment by tw2113** [comment]
Same people behind both, if I'm not mistaken.

**Comment by roughwriters** [comment]
I would definitely be interested in beta testing if possible.

**Comment by X-Raym** [comment]
@roughwriters 
Cool !
Take a look at [BadgeOS Bulk Actions Add-On](http://www.extremraym.com/en/downloads/badgeos-bulk-actions-add-on/).
You may also find [BadgeOS Extra Features Add-On](http://www.extremraym.com/en/downloads/badgeos-extra-features-add-on/) useful !
You can already buy the plugins, :)
Please tell me if they works for you, on a sandbox website.
Thanks, have fun with it !

**Comment by roughwriters** [comment]
Got it thanks.

What would make this plugin SUPER useful to me is if I could search based on an achievement earned. For bulk awarding, I usually need to do it for people who didn't trigger a certain badge because the series to earn that badge changed, and therefore the post achievements don't work toward the new badge.

But I still have to do that part manually.

Also, being able to search by name would be nice, too.

**Comment by X-Raym** [comment]
Hi !
Thanks for your purchase of the beta BadgeOS Bulk Actions Add-On !
Big update tomorrow:+ Searchable columns, thanks to DataTables
+ Sortable columns, thanks to DataTables
+ Pagination of long tables, thanks to DataTables
+ BuddyPress Groups integration
+ Groups integration
+ Update box
# Accessibility enhancements
# Performance optimizations
Here is a screenshot:https://monosnap.com/file/uczuXQqI61TssF8lXnBCuZzeyz896X.png

-----------------------------------------I'll evaluate your feature request,

Meanwhile, don't forget that you can use CSV input with user names, so you maybe you have ways to output users list that didn't have the desired badges, and paste this list in the CSV box ?

Thanks,
and have fun with the add-on !
 X-Raym
      De : roughwriters <notifications@github.com>
 À : opencredit/badgeos <badgeos@noreply.github.com> 
Cc : X-Raym <extremraym@yahoo.fr>
 Envoyé le : Mercredi 18 novembre 2015 2h17
 Objet : Re: [badgeos] Groups Actions - Addons Ideas (#385)
   
Got it thanks.What would make this plugin SUPER useful to me is if I could search based on an achievement earned. For bulk awarding, I usually need to do it for people who didn't trigger a certain badge because the series to earn that badge changed, and therefore the post achievements don't work toward the new badge.But I still have to do that part manually.Also, being able to search by name would be nice, too.—

**Comment by X-Raym** [comment]
@rougwriter
oh in fact there is a way simpler solution to do what you want.
Set maximum earning of your achievements to 1 and check Dont exceed maximum earning in the add-on form.
people without the achievement will have it, and people who already have it will not :P

**Comment by tw2113** [comment]
With that said, I'm going to close this issue. :)
