### ISSUE TITLE
BadgeOS LearnDash add-on

### ISSUE THREAD

**Issue by hopedo** [opencredit/badgeos#390]
Hello
I have downloaded the BadgeOS plugin, LearnDash plugin and the add-on for them to communicate. This is all on WordPress version 3.6.1. as required. I don't have the learnDash activities for the 'earn requirements'. I can't figure out what else it needs.
Please help.
Thanks

**Comment by tw2113** [comment]
If you haven't already, could you please start a thread at https://wordpress.org/support/plugin/badgeos-learndash-add-on and we'll look into it there. If you have, could you point me to the thread so I can check on it?
