### ISSUE TITLE
Achievements with maximum earnings of 1 awarded multiple times with submission review.

### ISSUE THREAD

**Issue by tw2113** [opencredit/badgeos#396]
BOS 1.4.3
Community 1.2.0

Click "approve" on the frontend review spot multiple times and achievement is being awarded multiple times and listed in user admin.

**Comment by mj445** [comment]
Note: Users are also receiving multiple badges (with max. earnings of 1) if the user completes a submission and then reloads the page (and clicks the "Resend Information" button). I've experienced this in Firefox.

**Comment by mj445** [comment]
Note: Users are also receiving multiple badges (with max. earnings of 1) if the user completes a submission and then reloads the page (and clicks the "Resend Information" button). I've experienced this in Firefox.

I'm confused by the "Enhancement" label, though, as I would consider this to be a bug. If my comment is misplaced, please let me know.

**Comment by tw2113** [comment]
probably just mislabeled.

**Comment by asahi-badgeos** [comment]
Hi @mj445 ,

Your issue has been resolved in 1.4.8.  Reloading the page will no longer trigger multiple earnings of the same achievement.
