### ISSUE TITLE
Cannot add steps! The "add step" option is not working

### ISSUE THREAD

**Issue by mialciva** [opencredit/badgeos#416]
Hello! I am new using BadgeOS (amazing let me say!!) but I am having some issues while editing my achievement types :( When I want the achievement to be earned by completing steps and go to the "Required steps" section, nothing happens when I click "Add step" Why is this? Please help me! I don't know if this happens to other users as well. I really appreciate the help of you guys!!

**Comment by tw2113** [comment]
If you could please, could you start a new thread over at http://www.wordpress.org/support/plugin/badgeos/ and we'll get things looked at there first. If we can confirm it's a bug, then we'll open up an issue here on GitHub. We try to leave GitHub for confirmed bugs and enhancement ideas, and the support forums for initial issues.

**Comment by mialciva** [comment]
I already did, thank you :)

**Comment by mialciva** [comment]
I already did, thank you :) 

The thread: https://wordpress.org/support/topic/cant-add-new-steps-add-step-button-is-not-working?replies=1

**Comment by rinkul123** [comment]
Hello I am having same issue with BadgeOS 1.4.4, When i click on "Add new step" it does nothing but when i opened my console i found this error: 

 Uncaught ReferenceError: badgeos_add_new_step is not definedpost.php?post=12681&action=edit:816 onclick

Please help solving this issue.
Advance Thanks

**Comment by tw2113** [comment]
@rinkul123 could you also start your own thread on the WordPress.org forums if you haven't already? If you have link me to it so I know for sure to have it opened in a browser tab.

**Comment by rinkul123** [comment]
Ok i found the solution ! The thing is JS and CSS files weren't accessible because of plugin folder permission was 0705. All you need to change the plugin folder permission and other sub-folder permission to 0755. It worked for me . Hope it will work for you guys too.

**Comment by tw2113** [comment]
Good to know you found a solution :)
