### ISSUE TITLE
Submitting for badges on refreshing the page.

### ISSUE THREAD

**Issue by pradeep46** [opencredit/badgeos#417]
After applying for the badges in frontend(wordpress, plugin : badgeOS), if I reload the page it keeps on submitting the form for the badge, the number of times I reload it.

**Comment by tw2113** [comment]
Hi @pradeep46, if you haven't already, could you start a support thread over on https://wordpress.org/support/plugin/badgeos and we'll get this taken care of there. If it's confirmed to be a bug, we'll return it here to GitHub, but we do all of our initial support on the support forums.
