### ISSUE TITLE
Comment on a Specific Post

### ISSUE THREAD

**Issue by atlantisremixed** [opencredit/badgeos#418]
When I have the trigger "Comment on a specific post" put on two different badges each with a unique post number, it fires both when I comment on either of the post. It should only fire the one in which the post # associated with the comment matches the post # associated with the badge requirements. Help! My students are completing 10 assignments in one post!

**Comment by tw2113** [comment]
#353

**Comment by atlantisremixed** [comment]
So, you are saying that this is not fixable and that it is not possible to have them comment on a specific type post and this has been known since July? Whey do you leave it in the system if you know it is broken?

Thanks
Sasha

**Comment by tw2113** [comment]
because it needs to be fixed.
