### ISSUE TITLE
Achievements list type variable occasionally empty.

### ISSUE THREAD

**Issue by tw2113** [opencredit/badgeos#422]
The $post_type_plural variable is set in both the ajax callback as well as the shortcode. There are cases where the current type DOES have an index, but it's an empty one. Because of this, the count for it does equal one, but we won't be able to get a post type object.

The fix is to simply check if we have a value in the first index value like below.

$post_type_plural = ( 1 == count( $types ) && !empty( $types[0] ) ) ? get_post_type_object( $args['type'] )->labels->name : __( 'achievements', 'badgeos' );

**Comment by tw2113** [comment]
For ajax file:

$current = current( $type );
$post_type_plural = ( 1 == count( $type ) && !empty( $current ) ) ? get_post_type_object( $current )->labels->name : __( 'achievements' , 'badgeos' );

**Comment by Reflecting** [comment]
I'm sorry, but I have no idea what you are saying exactly. All I know is that I created a new badge and "earned" it on my testing platform. It appears in BuddyPress Activity as well as in the widget that shows my earned badges, but it doesn't show up under the Achievements Tab of my BuddyPress profile. It was working yesterday with a community badge I created, but not working today with a standard badge created.

**Comment by tw2113** [comment]
Hi @Reflecting if you haven't yet, could you please start a support forum thread for this issue, and if you have already, point me to it so I know where exactly to go to address the topic there?

This GitHub issue probably isn't going to be related to yours.

**Comment by Reflecting** [comment]
I'm sorry, on the OS site it said to report bugs here and this is where the link took me. Thanks.

**Comment by tw2113** [comment]
No worries. This is the place for bugs, but we do try to make sure they're confirmed bugs as well. We'll get you taken care of :)

**Comment by tw2113** [comment]
Fixed in 422-empty-acievements-list-type

**Comment by tw2113** [comment]
Merged into alpha
