### ISSUE TITLE
Credly Integration Login Issues

### ISSUE THREAD

**Issue by michaeltieso** [opencredit/badgeos#437]
I have not been able to link to Credly.

> There was an error getting a Credly API Key: Please check your username and password.

The login and password I've confirmed several times and it does work on Credly. I checked on Credly but unable to find any reference to getting the API key.

**Comment by tw2113** [comment]
Sorry for the long delay with this one, Michael. This is in the Credly Settings page area when fetching an API key, correct?

**Comment by michaeltieso** [comment]
That's correct. The User ID and Password fields for Credly settings.

**Comment by michaeltieso** [comment]
That's correct. The User ID and Password fields for Credly settings.

**Comment by tw2113** [comment]
Not sure offhand. I was able to clear out my key and re-log in when I last tried a couple days ago.

**Comment by michaeltieso** [comment]
![screenshot](http://cld.wthms.co/1i9Xn+)

**Comment by michaeltieso** [comment]
Unrelated but I created my own API key on Credly itself but I'm getting this:

![screenshot](Course Badges+)
