### ISSUE TITLE
Conflict with WooCommerce

### ISSUE THREAD

**Issue by michaeltieso** [opencredit/badgeos#438]
Activating BadgeOS disables the ability to add products within an order on WooCommerce.

This is conflicting with the ability to use WooCommerce + Sensei + BadgeOS + BadgeOS Sensei extension.

![screenshot](http://cld.wthms.co/tLj8+)

**Comment by tw2113** [comment]
If you would be so kind, could you provide more detail on what is expected in the popup and what you're actually seeing? Would you be willing to potentially create an account for myself to log in and see things in action with? It'd help with debugging what may be going on.

**Comment by michaeltieso** [comment]
Thanks. Luckily this is easy to reproduce.

1. Simply install WooCommerce and BadgeOS.
2. Create a product with a sku
3. Add an order.
4. Then go on to try to add a product to the order. You will not be able to search.

This is what is supposed to appear if you search for an order:

![screenshot](http://cld.wthms.co/19dNA+)

If you disable BadgeOS, you'll be able to add products to an order again.

**Comment by tw2113** [comment]
Temporary fix that I whipped up.

```
/**
 * Hotfix for conflict with Select2 between BadgeOS and WooCommerce.
 */
function michaels_badgeos_woo_scripts_hotfix() {
	if ( !empty( $_GET ) && isset( $_GET['post_type'] ) && 'shop_order' == $_GET['post_type'] ) {
		remove_action( 'admin_init', 'badgeos_shortcodes_add_editor_button' );
	}
}
add_action( 'admin_init', 'michaels_badgeos_woo_scripts_hotfix' );

/**
 * Hotfix CSS for conflict with Select2 between BadgeOS and WooCommerce.
 */
function michaels_badgeos_woo_css_hotfix() {
	if ( !empty( $_GET ) && isset( $_GET['post_type'] ) && 'shop_order' == $_GET['post_type'] ) {
		echo '<style>#select2-drop { z-index: 999999; }</style>';
	}
}
add_action( 'admin_head', 'michaels_badgeos_woo_css_hotfix' );
```

**Comment by michaeltieso** [comment]
Thanks for the fix! That worked.

**Comment by tw2113** [comment]
Awesome, good to know it worked for at least one person. I had another similar issue report lack of success.

**Comment by tw2113** [comment]
Hey Michael. Can you test this with the latest of WooCommerce, but without the 2 filters above? I'm trying to recreate it so that I can permanently fix it in the plugin, but am suddenly not able to recreate.

I'm also not finding my hotfixes still in place, hiding somewhere in a corner, so that's why I'm wondering.

**Comment by solhuebner** [comment]
@michaeltieso could you test the latest WooCommerce without the hotfix?

**Comment by michaeltieso** [comment]
@solhuebner looks like we made some changes to WooCommerce which may have resolved this in the end. See https://github.com/woothemes/woocommerce/pull/8123

Thanks for checking in!

**Comment by tw2113** [comment]
Sweet. Thanks for helping confirm.
