### ISSUE TITLE
Badges OS "Search Submissions" function cant search all columns

### ISSUE THREAD

**Issue by jimbo1983** [opencredit/badgeos#442]
Hello all!  First time poster!
I am hoping there might be a quick fix for the search function inside of badgesOS.  When I go to the "Submissions" tab within the BadgesOS plugin, I can see all of the columns and submissions.  However, the search box along the top will only search the "Title" column, but I am hoping there might be a way to search any of the other columns too?  Mainly, if we could search the "Author" column as well, we would be ecstatic!  Thanks!
Jimbo

**Comment by tw2113** [comment]
I believe that would need to be custom-modified to include. It doesn't sound like anything we've done already either, so all of this is just out-of-box WordPress behavior, regarding the search.

Perhaps https://wordpress.org/plugins/search-everything/ will help out.

**Comment by jimbo1983** [comment]
tw2113, THANK YOU! It worked like a CHARM!!! We can search to our heart's content now!!!!!!

**Comment by tw2113** [comment]
Gonna close this one, as I think it's best left out of our hands.
