### ISSUE TITLE
badgeos-achievements.js not translating "Show Details", "Hide Details"

### ISSUE THREAD

**Issue by cyclingzealot** [opencredit/badgeos#462]
Any way to call Wordpress's translate function in JS?  I'm guessing the js has to pull the string via an http call?

```js
$ grep 'Hide Details' -rn plugins/badgeos/js/badgeos-achievements.js
190:			link.data( 'action', 'close' ).prop( 'class', 'show-hide-close' ).text( 'Hide Details' );
$ grep 'Show Details' -rn plugins/badgeos/js/badgeos-achievements.js
186:			link.data( 'action', 'open' ).prop( 'class', 'show-hide-open' ).text( 'Show Details' );
```

**Comment by tw2113** [comment]
Adding admin.js and credly-badge-builder.js to the list here. They all have strings that missed i18n.

**Comment by tw2113** [comment]
All for Alpha branch:
https://github.com/opencredit/badgeos/commit/a3e0923cf050a95c76154e5ad3d25cb8bfad5e45

https://github.com/opencredit/badgeos/commit/ba15df24d15c0ec2d00a9286d55d3ece8409be32

**Comment by cyclingzealot** [comment]
Not quite fixed.   Reverts correctly back to  "Montrer détails" but I get non-translated "Hide details" when I expand.  I think the string is missing from .po file.  Will check.

**Comment by cyclingzealot** [comment]
Non-translated "Hide details" fixed in https://github.com/opencredit/badgeos/pull/464
