### ISSUE TITLE
Bug in the get_achievement_earners function ?

### ISSUE THREAD

**Issue by Sym-O** [opencredit/badgeos#465]
Hi ! 
I encountering a very anoying bug about the module used to display the earners of an achievement at the end of its page. It happens that some users are shown on achievement page they do not have ! 
After some research on this I found that the function used to retrieve the earners seems to be bugged. Here is why : 
- The function simply search user_meta table using the key _badgeos_achievements and the value equal to the ID of the achievement. The compare method is "LIKE" or more accurately on mysql side (%LIKE%) (see function badgeos_get_achievement_earners in file achievement_functions.php)
- Thing is the value of the meta_key _badgeos_achievements is a complexe string were we can searching the appearance of the ID is not sufficient because we can get result we do not want. Example below

Here is a _badgeos_achievements string for a specific user who has earned 2 achievement, ID 187 and 405. But he appears on the achievement page of ID 436 whereas he does not own it... You can see that we can find the 3 digits of 436 in the date_earned field of the string. 

a:1:{i:1;a:2:{i:0;O:8:"stdClass":4:
{s:2:"ID";i:187;s:9:"post_type";s:6:"succes";s:6:"points";s:0:"";s:11:"date_earned";i:1435240871;}i:1;O:8:"stdClass":4:
{s:2:"ID";i:405;s:9:"post_type";s:6:"succes";s:6:"points";s:0:"";s:11:"date_earned";i:1436447447;}}}

That's how I end up with around 36 guys on a page where they should not appear... 
Do you confirm that ? If yes I'll try to fix this because I need a quick fix on that.

Thanks !

**Comment by tw2113** [comment]
https://github.com/opencredit/badgeos/issues/213
https://github.com/opencredit/badgeos/commit/0e5297ebd26f8a55346cbe449dae33aefa18266c

Easy enough commit/fix to get implemented on your own if you're needing it fixed asap. I'm hoping to get a 1.4.5 update out soon-sh and the issue above would be a part of the changelog for it.
