### ISSUE TITLE
Issue with shortcode

### ISSUE THREAD

**Issue by jscott87** [opencredit/badgeos#489]
Hi, I have attached a screenshot to the ticket. 
![badge shortcode not displaying](https://cloud.githubusercontent.com/assets/15094332/10436600/65004684-70f5-11e5-8b79-2204f7c716b0.png)

Our issue is that the achievements list shortcode seems to not be working on multiple pages. For one page the list will show "badges" as the user earns them...however, if we insert the shortcode on another page, that same function does not work and so therefore it says "No steps to display at this time". We are baffled by this, and hope to hear from you soon with your thoughts.

**Comment by tw2113** [comment]
Hi @jscott87 If you could, please start a thread over at https://wordpress.org/support/plugin/badgeos for this issue and we'll do all the debugging there. We leave GitHub issues for confirmed bugs and enhancement ideas.

Providing used shortcode parameters for each instance with the forum thread will help get things going a bit quicker as well. From the looks of the error, it's a case of coming down to no found results for some of the queries, and in the circled example above, steps specifically.
