### ISSUE TITLE
UTF-8 Problems in Edit User Profile

### ISSUE THREAD

**Issue by X-Raym** [opencredit/badgeos#491]
Hi,

Achievement title have some UTF-8 character problem in Edit User Profile page,
Screenshot(https://monosnap.com/file/z0fJ7M45WczdN3cYt2O1azzRrlNoxm.png)

The original text was Médaille, not M?daille

Thanks !

**Comment by tw2113** [comment]
Not managing to reproduce on my end. What language is your WP install in? It's possible that's playing a part in this.

![screen shot 2015-10-17 at 4 52 00 pm](https://cloud.githubusercontent.com/assets/484075/10561473/77c2118c-74ef-11e5-9419-06b144836ec2.png)

**Comment by X-Raym** [comment]
Hmmm it seems to only happens on my local installations.
I just tested online, maybe because of PHP newer version, I don't have this problem.
Well I guess there is nothing to correct here, someone could reopen this if needed.
