### ISSUE TITLE
User Update Points Log Entry

### ISSUE THREAD

**Issue by X-Raym** [opencredit/badgeos#493]
Hi,
according to badgeos_log_users_points() and badgeos_update_users_points() functions, updating users points (via User Edit Profile or via badgeos_update_users_points() call) should add log entries in the journal, shoudn't it ?
Actually, updating user points doesn't post any log entries in the journal.

**Comment by tw2113** [comment]
Good catch, and I get to facepalm myself because I'm the one that broke it 31bdbed00bff6c6badea5e43829096746b1cc002

Reverted those changes in alpha branch.

**Comment by X-Raym** [comment]
Thanks for the fix ! :)

**Comment by tw2113** [comment]
Fixed in 1.4.7 release.
