### ISSUE TITLE
Achievements not displaying on Badge

### ISSUE THREAD

**Issue by Eiseldora** [opencredit/badgeos#500]
I have a fresh install of BadgeOS and was trying to create some sample badges that require the completion of an activity i.e. another achievement type.

I created the achievements, and then the Badges. I've added a step in the badges for each of the achievements to be completed. I wanted to have the achievement text display on the badge, but for my sample badges it does not includes links to the required steps as displayed in the tutorial videos

How do I get the instructions(post body) from my activity to display on the badge page?

Is there a way to include only the the activities you want with a short code?
I tried entering this shortcode but its displaying all activities not just the one's I listed. '[badgeos_achievements_list type="activity" show_filter="true" show_search="true" orderby="menu_order" order="ASC" include="44769,995,1034,1023,44768" exclude="all" wpms="false"]' 

How do I make the steps listed on the badge link to the required activity.

Thank you for your support.

**Comment by Eiseldora** [comment]
![no links](https://cloud.githubusercontent.com/assets/8946787/11529970/8e4b44da-98a5-11e5-8c65-799fa1a95c41.png)

**Comment by tw2113** [comment]
Hi @Eiseldora.
If you would be so kind, could you start a new thread over at https://wordpress.org/support/plugin/badgeos for this? We keep GitHub issues for confirmed bugs, and utilize the wordpress.org forums for initial support. We'll get you taken care of over there.

Thanks
