### ISSUE TITLE
Website Login

### ISSUE THREAD

**Issue by designerhacks** [opencredit/badgeos#508]
It doesn't seem like I can get logged into the BadgeOs.org website.  Every time I try it just goes back to the login screen (and says I'm not logged in when I try to access the forums).

When I type in the wrong password, it takes me to the wordpress wp-admin page and tells me I put in the wrong password...

The issue is present on both chrome and safari

**Comment by tw2113** [comment]
Happening for me too, I'll let the proper people know. Closing the issue as it's not related to the plugin itself, but I do appreciate the report.

**Comment by tw2113** [comment]
Just as an update, you should be able to log in again as necessary.
