### ISSUE TITLE
Badgeos Completing Steps

### ISSUE THREAD

**Issue by jdcordova85** [opencredit/badgeos#509]
After completing steps I'm noticing the steps do not link up. Levels,quest,quest badges, etc do not link up with each other. 

I've found the badge is only earned on non-completing steps mainlty with auto-accepted submission. 

Also the label does not auto populate for me like in the demo videos. If it does it always default to say Earn "Badge" 1 time.  Even after I select quest or level it always says badge?

**Comment by tw2113** [comment]
hey @jdcordova85 do you think you could create a forum thread for this over at https://wordpress.org/support/plugin/badgeos ?

We try to keep the issues list here for confirmed bugs or enhancement ideas, and leave the initial support there.

To help streamline, when you are starting that thread, can you clarify the following:

What you're referring to regarding "not linking up" ? I'm confused by that part.
What related BadgeOS plugins are you using, if any.
Screenshots are also always helpful.

Notes: Also the labels should auto populate once you click save step.
