### ISSUE TITLE
In admin, when Max Earnings set to 0, when form reloads it overrides to 1

### ISSUE THREAD

**Issue by allmysystems** [opencredit/badgeos#511]
BadgeOS v 1.4.7. wp-content/plugins/badgeos/includes/meta-boxes.php line 131, std’=>’1’ - but when a DB entry is genuinely zero i.e. no maximum earnings, this is translated to 1 in the admin screen, presumably because the ‘std’ variable sets a default value when the DB entry is returned as blank or zero. Major issue if a user updates another part of this screen e.g. the description, doesn’t realise, submits the form, then the max earnings is set to 1 instead of 0. I've hacked the file to prevent that and made a note in our upgrade procedures to re-add the hack if the file is overwritten.

Verified after hack added as working correctly for other situations, e.g. when a maximum has been set e.g. 20 times, setting std to 0 still retains the value 20 in the field.

**Comment by tw2113** [comment]
Is this with the LearnDash addon installed/activated as well?

**Comment by allmysystems** [comment]
No, we only have the Leaderboard plugin and Community add ons plugins installed and activated.

Mark

Time for a refreshing approach to sustainable business growth?
We connect systems to deliver actionable insight about your business and customers.

Mark Pullar MSc MBCS
Managing Director
All My Systems Ltd, Room 1/10, 3M Buckley Innovation Centre, Firth Street, Huddersfield, HD1 3BD
mark@allmysystems.co.uk<mailto:mark@allmysystems.co.uk>
01422 824831
07739 881414

www.allmysystems.co.uk<http://www.allmysystems.co.uk/> | twitter.com/allmysystems | LinkedIn<https://www.linkedin.com/in/markpullar>

**Comment by tw2113** [comment]
I realize it's not an ideal/perfect solution, but setting to 99 would likely tide things over until some sort of solution can be worked out. Not sure how fast you expect someone to potentially get that high on one achievement.

**Comment by allmysystems** [comment]
Thanks Michael. We award badges when people take actions say, 250, 400 and 500 times.

We’ll stick with the hack so it’s foolproof for users – reapplying the hack is in our upgrade documentation



Time for a refreshing approach to sustainable business growth?
We connect systems to deliver actionable insight about your business and customers.

Mark Pullar MSc MBCS
Managing Director
All My Systems Ltd, Room 1/10, 3M Buckley Innovation Centre, Firth Street, Huddersfield, HD1 3BD
mark@allmysystems.co.uk<mailto:mark@allmysystems.co.uk>
01422 824831
07739 881414

www.allmysystems.co.uk<http://www.allmysystems.co.uk/> | twitter.com/allmysystems | LinkedIn<https://www.linkedin.com/in/markpullar>

**Comment by asahi-badgeos** [comment]
This item has been fixed in version 1.4.8.  Using a -1 will now allow for unlimited achievements.
