### ISSUE TITLE
SSL and https issue

### ISSUE THREAD

**Issue by joe704la** [opencredit/badgeos#533]
My site is running over https and I am unable to use this plugin because you guys are loading some files from a CDN and my site is blocking it since it is not being served over https. 

For example the file http://cdn.ckeditor.com/4.5.3/full/ckeditor.js.

**Comment by asahi-badgeos** [comment]
Thank you for the note Joel.  You can manually change the URL within the plugin to use a secure connection to CKEditor:

https://cdn.ckeditor.com/4.5.3/full/ckeditor.js.

We will update the plugin to prevent this going forward.

**Comment by asahi-badgeos** [comment]
Thank you for reporting this issue @joe704la .  This issue has been resolved in 1.4.8.1.
