### ISSUE TITLE
Conflicting with Boss Theme Slider

### ISSUE THREAD

**Issue by Darrenlibrarian** [opencredit/badgeos#535]
I updated to the latest version of BadgeOS on my WordPress site, I'm using a child theme of the Boss theme for Buddy Press, and the BadgeOS plugin update broke the homepage slider.  Here is the error log message:

(index):2072 Uncaught TypeError: $slider.slick is not a function(anonymous function) 
@ (index):2072i 
@ jquery.js?ver=1.12.3:2j.fireWith 
@ jquery.js?ver=1.12.3:2n.extend.ready 
@ jquery.js?ver=1.12.3:2K 
@ jquery.js?ver=1.12.3:2
ytprefs.js?ver=4.5.2:163 YT API ready

**Comment by asahi-badgeos** [comment]
Thank you for reporting this.  We will investigate and resolve this issue.  Any further detail that can be provided would be helpful.

**Comment by asahi-badgeos** [comment]
Hi @Darrenlibrarian ,

Can you confirm if you are using the _BuddyPress Edit Activity_ plugin?

**Comment by asahi-badgeos** [comment]
Hi @Darrenlibrarian .  This issue has been resolved in version 1.4.8.1.  Please update BadgeOS to the latest version.
