### ISSUE TITLE
Bug - site scripts not working since 1.4.8 update

### ISSUE THREAD

**Issue by stevecopeza** [opencredit/badgeos#537]
Hi BadgeOS support,

GREAT product, thanks.

I have a problem on my live site since upgrading to 1.4.8
I know it's the BadgeOS plugin as when I disable it the problem goes away.

When I got my article page there's a white bar at the top, the (mosaic tiled) articles don't load properly and wherever there are functional elements (calendar controls etc) it seems like they never correctly / completely load.

If i disable BadgeOS it goes back to normal.
I have downloaded the 1.4.8 files from Wordpress and reuploaded them, still happens.
I've done two restores and in each case it's only when the update is applied that it breaks.

I've also taken the trouble to restore to another site, run the update and I DONT have the problem there. 

I really would appreciate some assistance :)

Many thanks,
Steve

**Comment by asahi-badgeos** [comment]
Hi @stevecopeza ,

Thank you for your feedback, and I'm sorry you're experiencing this issue.  Can you please confirm which site theme you are currently using?

**Comment by asahi-badgeos** [comment]
Hi @stevecopeza ,

Can you confirm if you are using the _BuddyPress Edit Activity_ plugin?

**Comment by stevecopeza** [comment]
Hi all, 

I’m using the WOffice theme https://woffice.io
And LearnDash as the LMS

**Comment by stevecopeza** [comment]
Update - the issue is also happening on the restore site as well

**Comment by asahi-badgeos** [comment]
Hi @stevecopeza 

This issue has been resolved in version 1.4.8.1.  Please update BadgeOS to the latest version.  Thank you for taking the time to report this to us.
