### ISSUE TITLE
Bug - Possible javascript error cause many unrelated things to break in Boss theme

### ISSUE THREAD

**Issue by costyclan** [opencredit/badgeos#538]
I use the Buddyboss Boss theme and many parts of my site have broken after recent Badgeos update.
Pages using WPBakery visual composer seem to be most affected.
I contacted Buddyboss and they believe it's a possible javascript issue with the BadgeOS plugin and suggested I speak with Badgeos plugin developers.

**Comment by costyclan** [comment]
Definitely an issue with WPBakery Visual Composer plugin.

**Comment by asahi-badgeos** [comment]
This issue seems to be related to #535.  We will investigate the conflict.

Would you be able to provide more specific information on the errors you are seeing?

**Comment by costyclan** [comment]
Yes same issue as #535 
Slider is not displaying, anything with bullet, checkbox or dropdown is not showing at all, search results preview (drop down preview) not displaying. Looks like anything with javascript is not displaying.
Theme dev suggested  'a javascript error, which is causing many other unrelated'.

**Comment by costyclan** [comment]
very very eager to get BadgeOS working as we are set to launch our site within a week. Thank you for investigating.

**Comment by asahi-badgeos** [comment]
Hi @costyclan ,

I've installed the Boss theme on our testing sites, but I am not seeing the same conflicts you are.  Can you please confirm which version of the BuddyBoss theme you are working with?

If I can't replicate the issue you're experiencing in our environment, would you be open to providing me temporary access to your site to review the issue?

Thank you.

**Comment by costyclan** [comment]
I'm happy to provide temp access to my site.

How do I do that securely?




________________________________

**Comment by asahi-badgeos** [comment]
@costyclan 

You can contact me directly, at badgeos@asahitechnologies.com.
