### ISSUE TITLE
Acheivement Link doesnt show up on buddypress profile

### ISSUE THREAD

**Issue by excellins** [opencredit/badgeos#540]
I dont see any link to view my achievements on buddy press profile

**Comment by asahi-badgeos** [comment]
Hi,

Could you please try adding BadgeOS community Add-on for BadgeOS. This Add on will list the Achievement of an individual user if you click on the user profile.

https://wordpress.org/plugins/badgeos-community-add-on/

**Comment by excellins** [comment]
Hey Asahi, i already installed that, actually when i first installed the plugin and its community addon the link was visible on a profile name "achievements" clicking it took me to list of achievements, but later on while i configured the plugin the link dissapeared... all i did was delete the badge acheivement which came by default and included my acheivements. i deleted the plugin and installed it again but nothing changed my settings were still the same but the link was still visible on individual user profile

**Comment by excellins** [comment]
Hi Asahi, i installed the community addon yet it is still the same, earlier on there was a link, but later on the "acheivement" link was no more the only thing i did was delete the badge achievement which followed the plugin and created my own (which off-course shouldn't be an issue) now i removed the plugin and installed it again with the addon but no link to achievements

**Comment by excellins** [comment]
Hi Asahi, i installed the community addon yet it is still the same, earlier on there was a link, but later on the "acheivement" link was no more the only thing i did was delete the badge achievement which followed the plugin and created my own (which off-course shouldn't be an issue) now i removed the plugin and installed it again with the addon but no link to achievements

**Comment by asahi-badgeos** [comment]
Hi @excellins ,

I replied to your post on WordPress, but I wanted to make sure I replied to you here as well:

Hi Excellins,

For Achievements to appear in the BuddyPress profile, you will need to have the Achievement Types on your site configured to display within the Achievements tab. Can you confirm this has been set up?

1. In the BadgeOS menu, select Achievement Types, and click through each of the Achievement Types you have created.

[https://www.dropbox.com/s/xmww247jdnzn0vc/step%201.png?dl=0](url)

2. Ensure that Profile Achievements are checked off for each Achievement Type, in the BuddyPress Member Activity section.

[https://www.dropbox.com/s/a2wihk1j2scezrl/step%202.png?dl=0](url)

Can you please let me know if this configuration is completed?

**Comment by asahi-badgeos** [comment]
This issue was addressed on WordPress Support.
