### ISSUE TITLE
Problem with Maximum Earnings

### ISSUE THREAD

**Issue by msmcguire** [opencredit/badgeos#541]
I'm having a problem with the "maximum earnings" setting for an achievement. I have an achievement to be earned by "completing steps" with just one step--"Log in to Website" 1 time. I have it set for the user to earn 5 points with each completed login, and I have the maximum number of earnings set to 35. The problem I am having is that the points are awarded only the first time. The log entries show that the user "triggered wp_login" each time, but no points.

Are there any known issues regarding this? Any assistance would be greatly appreciated. Thanks so much for a great plugin.

Mike

**Comment by msmcguire** [comment]
In doing some testing, I see that the issue here is not present with version 1.4.7, but it is present with 1.4.8 and 1.4.8.1. What changed with these versions that has interfered with the expected behavior of the "maximum settings" option? Any advice? Thanks.

**Comment by asahi-badgeos** [comment]
Hi @msmcguire ,

I have tested and reproduced this issue.  We will resolve this shortly in a subsequent update.

**Comment by asahi-badgeos** [comment]
Hi @msmcguire ,

This item has now been resolved in 1.4.8.2.  Thank you for calling this to our attention.
