### ISSUE TITLE
select2 conflict at the backend with Custom Sidebars

### ISSUE THREAD

**Issue by JantoMcM** [opencredit/badgeos#549]
This is an issue across other plugins as well, but in our case it comes into play with Custom Sidebars. Net effect is that this plugin cannot load the conditions used to control the sidebars while BadgeOS is active. 

Console logs this as: "Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element."

**Comment by asahi-badgeos** [comment]
Hi @JantoMcM ,

I was unable to replicate this issue.  I was able to load Custom Sidebars, along with the configuration options, without an issue, and display them on my site.

https://www.dropbox.com/s/ci0vga0n58qnjir/custom%20sidebars.png?dl=0

Can you please provide more information on where you are seeing this error?

**Comment by JantoMcM** [comment]
My bad - proper plugin name is Content Aware Sidebars

[https://wordpress.org/plugins/content-aware-sidebars/](https://wordpress.org/plugins/content-aware-sidebars/)

The issue occurs in the backend when attempting to edit the conditions used for any sidebar - none of the existing conditions are displayed, and you can not add new ones (dropdown menu to select works, but nothing actually updates on the page). 

It's a relatively minor issue here, since it's easy to disable BadgeOS for the occasional new sidebar

**Comment by asahi-badgeos** [comment]
Thank you for clarifying.  I am now able to replicate this issue with this plugin.  Since it isn't high priority, we will place this on the backlog for a future release.

**Comment by intoxstudio** [comment]
I am the developer of Content Aware Sidebars and have been made aware of this issue.

It looks like BadgeOS enqueues an old version of select2 on custom admin pages where it isn't needed. Why is this?

**Comment by intoxstudio** [comment]
Doesn't seem like a fix that needs a PR, so I'll just post it here.
In badgeos/includes/class.BadgeOS_Editor_Shortcodes.php, change:

`add_action( 'admin_init', 'badgeos_shortcodes_add_editor_button' );`

to:

```
add_action( 'load-post.php', 'badgeos_shortcodes_add_editor_button' );
add_action( 'load-post-new.php', 'badgeos_shortcodes_add_editor_button' );
```

**Comment by JantoMcM** [comment]
Cheers Joachim

**Comment by asahi-badgeos** [comment]
We have updated the version of Select2 used in the BadgeOS plugin, which should officially resolve this issue.  This has been incorporated into version 1.4.8.3 of BadgeOS, now available for download from WordPress.  We will update the git repository here as well.

Thank you.

**Comment by lkraav** [comment]
@asahi-badgeos for GitHub repo, is the `master` branch going to be updated?
