### ISSUE TITLE
BadgeOs - Woocommerce 3.0.1 incompatibility?

### ISSUE THREAD

**Issue by phfeitosa** [opencredit/badgeos#566]
I found a problem involving BadgeOS plugin and woocommerce products edition.

I've deactivated all the other plugins to see that the error is with BadgeOS.

When the plugin is activeted is not possible to edit the products propreties in woocommerce products.

**Comment by Droidism** [comment]
@phfeitosa This problem might be because BadgeOS still uses the old Select2 library.

A.t.m. the latest Bos version in the WP repo is tested up to WP version 4.5.7, not really up-to-day one might say.

Sensei also depends on BadgeOS for the achievement and badge display, which might seem like a great idea at the time, but right now...

More info here: https://github.com/Automattic/sensei/issues/1776

**Comment by rachelsquirrel** [comment]
I can reproduce this on my test site. With BadgeOS active I'm unable to edit fields in the "Usage Restrictions" tab when creating or editing a coupon. There's a Select2 error message in the browser console:

![wc](https://cloud.githubusercontent.com/assets/7946521/25087035/040da218-2364-11e7-9b45-2a828ecabb8f.png)

**Comment by Droidism** [comment]
@rachelsquirrel This problem between WC 3.x.x and BadgeOS 1.4.8.2 is definitely a Select2 version conflict. 

Sad thing about this is that BadgeOS is considered to be in a maintenance phase. You can read more info in the [sticky post for the BadgeOS support section](https://wordpress.org/support/topic/support-and-development-status-2/) on WP.org:

**Comment by barifit** [comment]
Is there any way we can fix this?  I have had to deactivate Badge OS and no one can earn their badges as it also causes the product page to display the wrong name on my website.

**Comment by danjjohnson** [comment]
Also reported in 563035-zd-woothemes

**Comment by MindyPostoff** [comment]
Another report in 562433-zd-woothemes

**Comment by stukker01** [comment]
Any update on this? I'm having the same issue with BadgeOS v1.4.8.2 and WC v3.0.6

**Comment by merobal** [comment]
Just download the latest select2 library from here: https://github.com/select2/select2/ and update the files under /badgeos/js/select2/. This may help.

**Comment by johnnyr209** [comment]
This did not fix the issue with my site

**Comment by asahi-badgeos** [comment]
We have updated the Select2 Library used within BadgeOS, which should resolve the compatibility issue with WooCommerce.

The updated plugin is available for download from WordPress.  We will update the repository on here as well.
