### ISSUE TITLE
[badgeos_submission] shortcode issue

### ISSUE THREAD

**Issue by ckaklamanos** [opencredit/badgeos#584]
I am trying to embed a submission form into a standard WP post using the shortcode

[badgeos_submission achievement_id="xxx"].

The problem is that the upload attachment input field does not render at all.

The issue is caused by this code

https://github.com/opencredit/badgeos/blob/6b8624c6023f23d0d79a1bc38d6322de99d6a25c/includes/submission-actions.php#L1485

The use of $post->ID should be replaced by $args['achievement_id'] in order to get the  _badgeos_all_attachment_submission meta using the actual id of the achievement, not the ID of the current post.

**Comment by the-wooninjas** [comment]
@ckaklamanos This has been tackled on latest master branch. Please test this and let us know if it's working fine for you.

**Comment by rahilwazir** [comment]
@ckaklamanos This has been tackled on latest master branch. Please test this and let us know if it's working fine for you.

**Comment by ckaklamanos** [comment]
@rahilwazir thanks for the update.

I did a quick test and yes, now the $args['achievement_id'] is passed instead of $post_id, so the file submission input is shown properly. 

And I did a quick test with uploading and it works.

**Comment by rahilwazir** [comment]
@ckaklamanos Thank you for confirming
