### ISSUE TITLE
Attachments are not showing at the bottom of the Edit Submission screen.

### ISSUE THREAD

**Issue by ckaklamanos** [opencredit/badgeos#617]
The attachments are not showing at the bottom of the screen when the admin is on the Edit Submission screen.

![screenshot-dev courseconcierge com-2018-02-22-15-31-18](https://user-images.githubusercontent.com/3893309/36541092-76cd99c2-17e5-11e8-865e-c53897db3bc8.png)

This is because of this line of code

https://github.com/opencredit/badgeos/blob/29ef216814ccd53b3f4d6f14036d041efb3441bb/includes/submission-actions.php#L1735

In this line, the attachment post status is queried as "draft" or "publish", however, the actual post status in the DB is "inherit".

**Comment by rahilwazir** [comment]
This is fixed https://github.com/opencredit/badgeos/pull/615. Will be available at `1.4.11`, hoping for next week.

**Comment by rahilwazir** [comment]
We just released `1.4.11`, please test and report it back here. Closing for now.
