### ISSUE TITLE
Upgrade 3.0 DB & Upgrade Achievements button does not work

### ISSUE THREAD

**Issue by zishanj** [opencredit/badgeos#684]
I am using latest 3.2 version and Upgrade 3.0 DB button does not work when I click on it. Same is the issue with Upgrade Achievements buttons.

**Comment by zishanj** [comment]
seems like `jQuery` is not recognizing the click event at https://github.com/opencredit/badgeos/blob/263024ad66af4ed123d368c95e1f8982f4bfe572/js/admin.js#L260

**Comment by zishanj** [comment]
this is an issue with latest wordpress 5.2.2. Any update on this issue?

**Comment by FarooqAbdullah** [comment]
@zishanj 

We just tested the process with the latest WordPress 5.2.3 and found it is working fine.
Please follow the steps as indicated here: https://wordpress.org/support/topic/badgeos-3-0-major-update/

Thanks

**Comment by zishanj** [comment]
I should update to 5.2.3 then because on 5.2.2 the button does not work.

**Comment by zishanj** [comment]
I confirm that its working now on 5.2.3. Thanks!

**Comment by hallshouse** [comment]
Is there a visual indication that this button does something?
I had my client purchase the core and many other BadgeOS add-ons.
I'm running WP 5.3.2, PHP7.3 MySQL 5.7
I click the button and nothing happens.
No console errors, no server errors either.
I also see when I go to activate the logs and debug, it keeps sending my to wp-admin/options.php
