### ISSUE TITLE
Error message: Unknown column 'actual_date_earned'

### ISSUE THREAD

**Issue by nsteinfeld** [opencredit/badgeos#795]
When manually issuing Open Badges through the user profile page, badges are created with entry ID 0 and never showed up on the user's profile page.
e.g. Badge-0-248.png, Badge-0-1430.png

WordPress database error: `[Unknown column 'actual_date_earned' in 'field list']`
There isn't an `actual_date_earned` column in the wp_badgeos_achievements table, but there is a `date_earned` column.

I issued our last badge on September 8 without any issues, so the problem started somewhere between September 8 and September October 14. If I see this correctly in the Changelog BadgeOS 3.6.6 was released Oct.2? Was the issue caused by the new release?

### Steps to Reproduce

  1. Set up Open Badges
  2. Add `$wpdb->show_errors()` after `$success = $wpdb->insert()` in `function badgeos_update_user_achievements()`. 
  3. Issue Open Badge through any user's profile page (/wp-admin/user-edit.php).

Result: 
Unknown column 'actual_date_earned'

- BadgeOS: 3.6.6
- BadgeOS Community Add-On 1.2.10
- WordPress: 5.5.1

**Comment by the-wooninjas** [comment]
Issue has been addressed and fixed, please upgrade to latest version 3.6.12. Thank you
