### ISSUE TITLE
502 error in badgeos tools

### ISSUE THREAD

**Issue by markvillanueva08** [opencredit/badgeos#819]
### Description
When I do go in badgeos -> tools the page goes 502

I already deactivate all of the plugins and I already changed the theme 

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

### Product Versions

- BadgeOS: 3.6.9
- WordPress: Version 5.6.1

### Additional Information

N/A

**Comment by the-wooninjas** [comment]
Please update to latest version. Thank you.
