### ISSUE TITLE
Learndash & Buddyboss profile page crash with Badgeos

### ISSUE THREAD

**Issue by Colfu** [opencredit/badgeos#820]
### Description
After activating Badgeos and BadgeOS LearnDash Add-On, viewing my profile page creates an unexpected error.

### Steps to Reproduce

  1. Activating Badgeos and BadgeOS LearnDash Add-On 
  2. Navigate to My Courses from the Profile dropdown menu
  3.

**Actual result:**
{"@context":"https:\/\/w3id.org\/openbadges\/v2","type":"Assertion","id":"\/members\/col\/courses\/?bg=0&eid=0&uid=0","recipient":{"type":"email","hashed":true,"salt":"BADGEOSOBI","identity":"sha256$ddbc8b27496e2e6991d13816769fd55c169583126e43fab5ea7d282b2df8d73a"},"badge":"\/members\/col\/courses\/?bg=0&eid=0&uid=0","issuedOn":"2021-03-08T17:02:54+00:00","image":"https:\/\/futube.co.uk\/wp-content\/plugins\/badgeos\/images\/default_badge.png","verification":{"type":"HostedBadge","verificationProperty":"id"}}

**Expected result:**
My courses page.

### Product Versions

- BadgeOS: 3.6.9
- BadgeOS LearnDash Add-On
- WordPress: WordPress 5.6.2 running BuddyBoss Child theme.
- BuddyBoss Platform 1.5.7.2

### Additional Information

N/A

**Comment by vladinko0** [comment]
One workaround is to create and set 4 pages in OB Integration section.
