### ISSUE TITLE
Not Earned Image - Not Saving

### ISSUE THREAD

**Issue by MikeGriffithsCanada** [opencredit/badgeos#849]
### Description
Since upgrading to 3.6.11 uploading of "Not Earned Image" has stopped working. Instead of saving the selected image, it defaults back to the "?" image. 

### Steps to Reproduce

  1. Navigate to an existing badge and select "Edit" 
  2. Scroll to Not Earned Image and select "Remove image" 
  3. Use "Set Image" to select a new image from Media Library or Upload
  4. Click on "Update" to save the badge settings

**Actual result:**

The "Not Earned" image reverts back to "?" image

**Expected result:**

The "Not Earned" image is set to the one seleected

### Product Versions

- BadgeOS: 3.6.11
- WordPress: 5.7.2

### Additional Information

N/A

**Comment by the-wooninjas** [comment]
This issue is been addressed and fixed is added in v3.6.12. Thank you
