### ISSUE TITLE
 Badge for submitting in specific categories / using specific tags

### ISSUE THREAD

**Issue by Kovah** [opencredit/badgeos#86]
It would be awesome if the following feature could be added:
The user submits a post into the "cars" category and receives the badge for submitting the first post to this category. Or a badge for submitting 100 posts to this category.
The same could be done with tags.

**Comment by bklevence** [comment]
After doing some further research into this I found:
![image](https://cloud.githubusercontent.com/assets/980262/6803710/d84f0678-d20f-11e4-9d67-a0d57c5b6e4a.png)
http://instructionaldesign.ubc.ca/2015/01/30/badgeos-for-wordpress/?login

Talking to them may help, I'm going to attempt to work on something this week. We'll see what happens..

**Comment by dcmcshan** [comment]
The link above no longer works.  This would be a very useful feature, though.  Thoughts on implementing?
