### ISSUE TITLE
Log entries, caching and bloat

### ISSUE THREAD

**Issue by rastarr** [opencredit/badgeos#90]
This probably links to #38 and I posted to http://wordpress.org/support/topic/log-entries-and-caching?replies=1 also

On a low volume (as far as BadgeOS goes) site, I still have 164 pages of log entries so I can only imagine what a busy site would have.

I just discovered that because these log entries are registered as a valid custom post type that they also get cached by caching plugin like my WPSuperCache so it's been caching thousands of extra and unneeded pages in the system. That's kinda bad for performance and unnecessary resources in many ways.

Can log entries please be changed to plain text in one file?
What's the impact, if any, on deleting all log entries?
Do log entries help keep track on awards in any way?

**Comment by lkraav** [comment]
Heya @brichards @tw2113 I've reached out in e-mail wrt how BadgeOS 1.4 log system ended up back then. Hoping y'all could shed some light on a few dark corners we're facing trying to migrate a site off this plugin :pray:
